export type Prospect<T = {}> = T & {
  ProspectID: string;
  ProspectAutoId: string;
  FirstName: string;
  LastName: string;
  EmailAddress: string;
  Company: string | null;
  Origin: string;
  Phone: string;
  Mobile: string | null;
  Fax: string | null;
  Website: string | null;
  TimeZone: string | null;
  Region: string | null;
  JobTitle: string | null;
  Source: string;
  SourceMedium: string;
  Notes: string | null;
  SourceCampaign: string;
  SourceContent: string;
  DoNotEmail: string;
  DoNotCall: string;
  ProspectStage: string;
  Grade: string | null;
  Score: string;
  Revenue: string | null;
  EngagementScore: string;
  TotalVisits: string;
  PageViewsPerVisit: string;
  AvgTimePerVisit: string;
  RelatedProspectId: string | null;
  ProspectActivityId_Min: string;
  ProspectActivityDate_Min: string;
  Web_Referrer: string;
  Web_RefKeyword: string;
  ProspectActivityId_Max: string;
  ProspectActivityName_Max: string;
  ProspectActivityDate_Max: string;
  ImportTransactionId: string | null;
  RelatedLandingPageId: string | null;
  FirstLandingPageSubmissionId: string | null;
  FirstLandingPageSubmissionDate: string | null;
  OwnerId: string;
  CreatedBy: string;
  CreatedOn: string;
  ModifiedBy: string;
  ModifiedOn: string;
  LeadConversionDate: string | null;
  StatusCode: string;
  StatusReason: string;
  DeletionStatusCode: string;
  IsLead: string;
  mx_Street1: string | null;
  mx_Street2: string | null;
  mx_City: string | null;
  mx_State: string | null;
  mx_Country: string | null;
  mx_Zip: string | null;
  mx_Geography: string | null;
  mx_DOB: string | null;
  mx_Anniversary: string | null;
  mx_FaceBookURL: string | null;
  mx_TwitterURL: string | null;
  mx_LinkedInURL: string | null;
  JobTitleLevel: string | null;
  mx_Date_1: string | null;
  mx_Date_2: string | null;
  mx_Date_3: string | null;
  mx_Date_4: string | null;
  mx_Location: string | null;
  mx_Pincode: string | null;
  mx_Grade: string | null;
  mx_Grade_1: string | null;
  mx_Olark_Group: string | null;
  mx_Page_Source: string | null;
  mx_DRPDN: string | null;
  mx_UTM_Term: string | null;
  mx_UTM_Site: string | null;
  mx_UTM_Device_Type: string | null;
  mx_UTM_Network: string | null;
  mx_College: string | null;
  mx_CB_TEST: string | null;
  mx_Date_test: string | null;
  mx_Lead_Status: string | null;
  mx_IsBuyer: string | null;
  mx_Age: string | null;
  mx_Product: string | null;
  mx_Secondary_Email: string | null;
  mx_Education_Board: string | null;
  mx_Phone_Type: string | null;
  mx_TimeTest: string | null;
  mx_Test123: string | null;
  mx_test1: string | null;
  mx_State2: string | null;
  LastModifiedOn: string;
  NotableEvent: string;
  NotableEventdate: string;
  SourceReferrer: string;
  LastVisitDate: string;
  LeadAge: string;
  PhotoUrl: string | null;
  mx_Percentag: string | null;
  TwitterId: string | null;
  FacebookId: string | null;
  LinkedInId: string | null;
  SkypeId: string | null;
  GTalkId: string | null;
  GooglePlusId: string | null;
  QualityScore01: string | null;
  mx_test_url: string | null;
  mx_MSDD: string | null;
  StageRottingFlagStatus: string | null;
  StageRottingFlagMessage: string | null;
  StageRottingFlagModifiedOn: string | null;
  StageRottingFlagAdditionalInfo: string | null;
  StageRottingFlagLevel: string | null;
  MailingPreferences: string;
  mx_first_dropdown: string | null;
  mx_Perc2: string | null;
  mx_Second_dropdown: string | null;
  OwnerIdName: string;
  OwnerIdEmailAddress: string;
  Groups: string | null;
  CreatedByName: string;
  ModifiedByName: string;
  CreatedByName1: string;
  ModifiedByName1: string;
  OwnerIdEmailAddress1: string;
  OwnerIdName1: string;
  Total: string;
  CanUpdate: string;
};
